# Generated by Django 4.2.7 on 2024-02-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(default=0, max_length=254),
        ),
    ]
