# Generated by Django 4.2.7 on 2024-02-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owner", "0002_invoice_invoice_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
