# Generated by Django 4.2.7 on 2024-02-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owner", "0005_postagesettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postagesettings",
            name="free_postage",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="postagesettings",
            name="standard_cost",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
