# Generated by Django 4.2.7 on 2024-02-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owner", "0006_alter_postagesettings_free_postage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="postagesettings",
            name="express_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
