# Generated by Django 4.2.7 on 2024-02-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owner", "0008_remove_postagesettings_express_cost_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Voucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voucher_code", models.CharField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("discount", models.PositiveIntegerField()),
            ],
        ),
    ]
