# Generated by Django 4.2.7 on 2024-02-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owner", "0009_voucher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voucher",
            name="discount",
            field=models.PositiveIntegerField(help_text="Discount - % of TOTAL"),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="end_date",
            field=models.DateField(help_text="Last Day of Validity "),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="start_date",
            field=models.DateTimeField(help_text="First Day of Validity"),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="voucher_code",
            field=models.CharField(help_text="Discount Code"),
        ),
    ]
