# Generated by Django 4.2.7 on 2024-02-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owner", "0010_alter_voucher_discount_alter_voucher_end_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("newsletter_email", models.EmailField(max_length=254)),
            ],
        ),
    ]
