# Generated by Django 4.2.7 on 2024-02-24 19:16

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("owner", "0011_newsletter"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField()),
                ("body", tinymce.models.HTMLField()),
                ("to_address", models.ManyToManyField(to="owner.newsletter")),
            ],
        ),
    ]
