# Generated by Django 4.2.7 on 2024-02-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owner", "0012_newsletteremail"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletteremail",
            name="status",
            field=models.IntegerField(choices=[(0, "Draft"), (1, "Sent")], default=0),
        ),
    ]
