# Generated by Django 4.2.7 on 2024-02-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owner", "0014_newsletteremail_date_sent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newsletteremail",
            old_name="status",
            new_name="email_status",
        ),
        migrations.AlterField(
            model_name="voucher",
            name="start_date",
            field=models.DateField(help_text="First Day of Validity"),
        ),
    ]
