# Generated by Django 4.2.7 on 2024-02-26 09:52

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):
    dependencies = [
        ("owner", "0016_rename_email_status_newsletteremail_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletteremail",
            name="body",
            field=djrichtextfield.models.RichTextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="newsletteremail",
            name="subject",
            field=models.CharField(max_length=200),
        ),
    ]
