# Generated by Django 4.2.7 on 2024-02-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owner", "0017_alter_newsletteremail_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletteremail",
            name="body",
            field=models.TextField(max_length=10000),
        ),
    ]
