# Generated by Django 4.2.7 on 2024-02-26 13:58

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):
    dependencies = [
        ("owner", "0018_alter_newsletteremail_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletteremail",
            name="body",
            field=djrichtextfield.models.RichTextField(max_length=10000),
        ),
    ]
