# Generated by Django 4.2.7 on 2024-03-02 10:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("owner", "0019_alter_newsletteremail_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletteremail",
            name="body",
            field=ckeditor.fields.RichTextField(max_length=10000),
        ),
    ]
