# Generated by Django 4.2.7 on 2024-03-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owner", "0020_alter_newsletteremail_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voucher",
            name="voucher_code",
            field=models.CharField(help_text="Discount Code", unique=True),
        ),
    ]
