# Generated by Django 4.2.7 on 2024-03-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owner", "0021_alter_voucher_voucher_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="postagesettings",
            name="minimum_order",
            field=models.DecimalField(
                decimal_places=2,
                default=5,
                help_text="Amount in € that VAULT needs to be over for processing the order",
                max_digits=5,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="postagesettings",
            name="express_delivery",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Cost of express delivery - % of VAULT ",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="postagesettings",
            name="free_postage",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Amount in € that VAULT needs to be over for free delivery",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="postagesettings",
            name="standard_delivery",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Cost of standard delivery - % of VAULT ",
                max_digits=5,
            ),
        ),
    ]
