# Generated by Django 4.2.7 on 2024-03-07 12:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("owner", "0022_postagesettings_minimum_order_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Invoice",
        ),
    ]
