# Generated by Django 4.2.7 on 2024-03-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owner", "0023_delete_invoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postagesettings",
            name="minimum_order",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Amount in € VAULT needs to be over",
                max_digits=5,
            ),
        ),
    ]
