# Generated by Django 4.2.7 on 2024-02-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profilemanager", "0002_alter_userprofile_profile_picture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="marketing",
            new_name="marketing_email",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="marketing_phone",
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="marketing_sms",
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
