# Generated by Django 4.2.7 on 2024-03-19 08:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profilemanager", "0006_alter_userprofile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="user_wishlist",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=254),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
