# Generated by Django 4.2.7 on 2024-03-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_option",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="invoice",
            field=models.FileField(default=0, upload_to="invoices/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="voucher",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
