# Generated by Django 4.2.7 on 2024-03-03 09:44

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0002_order_delivery_option_order_invoice_order_voucher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address_1",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="country",
            field=django_countries.fields.CountryField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="county",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="first_name",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="last_name",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="phone_number",
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="post_code",
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
