# Generated by Django 4.2.7 on 2024-03-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0005_alter_order_invoice_alter_order_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="voucher",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
