# Generated by Django 4.2.7 on 2024-01-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="name",
            new_name="category_name",
        ),
        migrations.RemoveField(
            model_name="category",
            name="slug_name",
        ),
        migrations.AddField(
            model_name="category",
            name="category_code",
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
