# Generated by Django 4.2.7 on 2024-01-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0002_rename_name_category_category_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="category_sku",
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
