# Generated by Django 4.2.7 on 2024-02-02 18:50

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0007_alter_category_category_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=["middle", "center"],
                force_format="WEBP",
                keep_meta=True,
                quality=75,
                scale=None,
                size=[400, 400],
                upload_to="category_images/",
            ),
        ),
    ]
