# Generated by Django 4.2.7 on 2024-02-02 18:50

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0008_alter_category_category_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=254)),
                ("item_sku", models.CharField(blank=True, max_length=254, null=True)),
                ("item_description", models.TextField()),
                (
                    "different_sizes",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "sizes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "different_values",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "values",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("price_per_unit", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "image_1",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=["middle", "center"],
                        force_format="WEBP",
                        keep_meta=True,
                        quality=75,
                        scale=None,
                        size=[400, 400],
                        upload_to="category_images/",
                    ),
                ),
                (
                    "image_2",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=["middle", "center"],
                        force_format="WEBP",
                        keep_meta=True,
                        quality=75,
                        scale=None,
                        size=[400, 400],
                        upload_to="category_images/",
                    ),
                ),
                (
                    "image_3",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=["middle", "center"],
                        force_format="WEBP",
                        keep_meta=True,
                        quality=75,
                        scale=None,
                        size=[400, 400],
                        upload_to="category_images/",
                    ),
                ),
                (
                    "item_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="items.category",
                    ),
                ),
            ],
        ),
    ]
