# Generated by Django 4.2.7 on 2024-02-02 18:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0009_item"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
    ]
