# Generated by Django 4.2.7 on 2024-02-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0010_alter_category_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="item_category",
        ),
        migrations.AddField(
            model_name="item",
            name="item_category",
            field=models.ManyToManyField(to="items.category"),
        ),
    ]
