# Generated by Django 4.2.7 on 2024-02-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0011_remove_item_item_category_item_item_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_sku",
            field=models.CharField(max_length=254, null=True),
        ),
    ]
