# Generated by Django 4.2.7 on 2024-02-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0012_alter_item_item_sku"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="different_sizes",
            field=models.IntegerField(
                choices=[
                    (0, "No - Item has no sizes"),
                    (1, "Yes - Item has different sizes"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="different_values",
            field=models.IntegerField(
                choices=[
                    (0, "No - Item has no values"),
                    (1, "Yes - Item has different values"),
                ],
                default=0,
            ),
        ),
    ]
