# Generated by Django 4.2.7 on 2024-02-03 14:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0014_alter_item_item_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="different_sizes",
            field=models.IntegerField(
                choices=[
                    (0, "No - Item has no sizes"),
                    (1, "Yes - Item has different sizes"),
                ],
                default=0,
                help_text="Select yes if item comes in different package sizes",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="different_values",
            field=models.IntegerField(
                choices=[
                    (0, "No - Item has no values"),
                    (1, "Yes - Item has different values"),
                ],
                default=0,
                help_text="Select yes if item comes in different values",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="sizes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                help_text='Separate sizes by comma ","',
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="values",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                help_text='Separate values by comma ","',
                null=True,
                size=None,
            ),
        ),
    ]
