# Generated by Django 4.2.7 on 2024-02-03 20:04

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0015_alter_item_different_sizes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image_1",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=["middle", "center"],
                force_format="WEBP",
                keep_meta=True,
                quality=75,
                scale=None,
                size=[400, 400],
                upload_to="item_images/",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="image_2",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=["middle", "center"],
                force_format="WEBP",
                keep_meta=True,
                quality=75,
                scale=None,
                size=[400, 400],
                upload_to="item_images/",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="image_3",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=["middle", "center"],
                force_format="WEBP",
                keep_meta=True,
                quality=75,
                scale=None,
                size=[400, 400],
                upload_to="item_images/",
            ),
        ),
    ]
