# Generated by Django 4.2.7 on 2024-02-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0016_alter_item_image_1_alter_item_image_2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_name",
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
