# Generated by Django 4.2.7 on 2024-02-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0017_alter_item_item_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_vat_rate",
            field=models.IntegerField(
                choices=[
                    (0, "23 % VAT"),
                    (1, "13.5 % VAT"),
                    (2, "9 % VAT"),
                    (3, "0 % VAT"),
                ],
                default=0,
                help_text="Select yes if item comes in different package sizes",
            ),
        ),
    ]
