# Generated by Django 4.2.7 on 2024-02-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0019_alter_item_item_vat_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="stock",
            field=models.IntegerField(default=0),
        ),
    ]
