# Generated by Django 4.2.7 on 2024-02-04 11:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0020_item_stock"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="stock",
            new_name="item_stock",
        ),
    ]
