# Generated by Django 4.2.7 on 2024-02-04 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("items", "0022_item_item_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_likes",
            field=models.ManyToManyField(
                blank=True, related_name="item_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
