# Generated by Django 4.2.7 on 2024-02-04 19:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0024_invoice"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Invoice",
        ),
    ]
