# Generated by Django 4.2.7 on 2024-02-05 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0025_delete_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="date_added",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
