# Generated by Django 4.2.7 on 2024-02-12 15:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("items", "0026_item_date_added"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_dislikes",
            field=models.ManyToManyField(
                blank=True, related_name="item_dislikes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
