# Generated by Django 4.2.7 on 2024-01-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=254)),
                (
                    "slug_name",
                    models.SlugField(blank=True, max_length=255, unique=True),
                ),
                (
                    "category_image",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
            ],
        ),
    ]
